website/home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('policy/', views.policy, name='policy'),
    path('privacy-policy/', views.privacy_policy, name='privacy'),
    path('terms-and-conditions/', views.terms_conditions, name='termsAndConditions'),
    path('refund-policy/', views.refund_policy, name='refund'),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('iframe-contact/', views.contact_frame, name='contact-frame'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('announcements/', views.announcements, name='announcements'),
    path('admin-dashboard/', views.admindashboard, name='admin_dashboard'),
    # Auth
    path('logout/', views.logoutuser, name='logout'),
    path('team-dashboard/<int:pk>', views.teammember_dashboard, name='teammember-dashboard'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from home import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # AUTH
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='auth/reset_link.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='auth/set_pass.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='auth/reset_done.html'),
         name='password_reset_complete'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(template_name='auth/reset_pass.html'),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('monetary.urls')),
]

website/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField


class TeamMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    referral_code = models.CharField(max_length=16)

    def __str__(self):
        return f"{self.user.username}"


class Participant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    referrer = models.ForeignKey(TeamMember, on_delete=models.SET_NULL, null=True, blank=True)
    contact_number = PhoneNumberField()
    paid = models.BooleanField(null=True, blank=True)
    order_id = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.first_name}"

    @classmethod
    def filter_paid(cls):
        return cls.objects.filter(paid=True)


class Announcement(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}"


class EventCategory(models.Model):
    name = models.CharField(max_length=80)
    index = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = 'Event Category'
        verbose_name_plural = 'Event Categories'
        ordering = ('index',)

    def __str__(self):
        return f"{self.name}"


def get_image_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "event_images/%s-%s" % (slug, filename)


class Event(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField()
    date = models.DateField(blank=True, null=True)
    image_1 = models.ImageField(blank=True, null=True, upload_to=get_image_filename, verbose_name='First Image')
    image_2 = models.ImageField(blank=True, null=True, upload_to=get_image_filename, verbose_name='Second Image')
    category = models.ForeignKey(EventCategory, on_delete=models.SET_NULL, null=True, blank=True)
    index = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'
        ordering = ('index',)

    def __str__(self):
        return f"{self.title}, {self.category}"

website/home/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.decorators.http import require_http_methods

from .models import Announcement, TeamMember, EventCategory, User, Participant


def home(request):
    event_categories = EventCategory.objects.all()
    return render(request, 'home/home.html', dict(
        event_categories=event_categories,
    ))


def contact_us(request):
    return render(request, 'home/contact-us.html')


def policy(request):
    return render(request, 'home/policies.html')


def refund_policy(request):
    return render(request, 'home/refundPolicy.html')


def terms_conditions(request):
    return render(request, 'home/termsAndConditions.html')


def privacy_policy(request):
    return render(request, 'home/privacyPolicy.html')


@xframe_options_sameorigin
def contact_frame(request):
    return render(request, 'home/contact-template.html')


@login_required
def dashboard(request):
    return render(request, 'home/dashboard.html')


@login_required
def profile(request):
    try:
        participants = request.user.teammember.participant_set.filter(paid=True)
        referral_count = participants.count()
    except ObjectDoesNotExist:
        referral_count = None
    return render(request, 'home/profile.html', dict(
        referral_count=referral_count,
    ))


@login_required
def teammember_dashboard(request, pk):
    if not (request.user.id == pk or request.user.is_staff):
        print('fucked')
        raise PermissionDenied

    try:
        user = User.objects.get(id=pk)
        participants = user.teammember.participant_set.filter(paid=True)
        referral_count = participants.count()
    except ObjectDoesNotExist:
        print('fucked backwards')
        raise PermissionDenied

    return render(request, 'home/team_dashboard.html', dict(
        referral_count=referral_count,
        participants=participants,
    ))


@login_required
def announcements(request):
    announcements_ = Announcement.objects.all().order_by('created_on')
    return render(request, 'home/announcements.html', {'announcements': announcements_})


@require_http_methods(["POST"])
@login_required
def logoutuser(request):
    logout(request)
    messages.add_message(request, messages.INFO, 'Logout successful')
    return redirect('/')


@staff_member_required
def admindashboard(request):
    teammembers = TeamMember.objects.annotate(referrals=Count('participant', filter=Q(participant__paid=True)))
    all_participants = Participant.filter_paid()
    total_participants = all_participants.count()
    nonreferral_participants = all_participants.filter(referrer=None).count()
    total_referrals = total_participants - nonreferral_participants

    return render(request, 'home/adminDashboard.html', dict(
        teammembers=teammembers,
        total_participants=total_participants,
        nonreferral_participants=nonreferral_participants,
        total_referrals=total_referrals,
    ))

website/home/templates/home/adminDashboard.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <br>
    <hr>
    <br>
    <div class="alert alert-primary" role="alert" style="width: 60%; margin: auto; text-align: center;">
        Total Participants &nbsp #{{ total_participants }} |
        Total Non-Referrals &nbsp #{{ nonreferral_participants }} |
        Total Referrals &nbsp #{{ total_referrals }} |
    </div>
    <br>

    {% for teammember in teammembers %}
        <a href="{% url 'teammember-dashboard' teammember.user.id %}" style="text-decoration: none">
            <div class="alert alert-primary" role="alert" style="width: 60%; margin: auto; text-align: center;">
                {{ teammember.user.username }}&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbsp{{ teammember.referrals }}
            </div>
        </a>
    {% endfor %}

{% endblock %}

website/home/templates/home/announcements.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'home/css/announcement.css' %}">
        <title>TCB - Announcements</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'home/img/icon.png' %}"/>
    </head>
    <body>
        <div class="container">

            <!--NAV BAR-->
            <nav class="main-nav">
                <a href = "{% url 'home' %}"><img src="{% static 'home/img/title.png' %}" alt="Microsoft" class="logo"></a>
                {% if user.is_authenticated %}
                <ul class="right-menu">
                    <li><a href="{% url 'announcements' %}" style = "color: #262626; text-decoration: none"><i class="fas fa-bell"></i> Announcements </a></li>
                    <li><a href="{% url 'profile' %}" style = "color: #262626; text-decoration: none"><i class="fas fa-user"></i> {{user.username}} </a></li>
                    <li style="cursor: pointer;">
                    <form method="POST" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" style="border: none; background-color: white; outline: none; font-family: 'aquire'; margin-top: 0.15rem"><i class="fas fa-sign-out-alt"></i> Logout </button>
                    </form>
                    </li>
                </ul>
                {% endif %}
            </nav>
            <br>
            <!--ShowCase-->
            <header class="showcase" style="background: url({% static 'home/img/tcb_5.png' %}) no-repeat center center/cover;">
                <img src = "{% static 'home/img/logo3.png' %}" height = "50%">
                <h2>The Code Builder</h2>
                <p>
                    The Code Builder is a series of a wide range of events to be held in the month of October 2020, completely safe and virtual.
                </p>
                <a href="{% url 'home' %}" class="btn">
                    Home <i class="fas fa-chevron-right"></i>
                </a>
            </header>
            <br>
        </div>

        {% for announcement in announcements %}
        <div class="courses-container">
            <div class="course">
                <div class="course-preview" style="background: url({% static 'home/img/tcb_5.png' %}) no-repeat center center/cover; width: 50%">
                    <h5>Announcement {{ forloop.counter }}</h5>
                    <h2>{{ announcement.title }}</h2>
                </div>
                <div class="course-info">
                    <h3>{{ announcement.content }}</h3>
                </div>
            </div>
        </div>
        {% endfor %}
    </body>
</html>

website/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/announcement.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'home/img/icon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>The Code Builder</title>
</head>
<body>
	<div class="menu-btn">
    <i class="fas fa-bars fa-2x"></i>
    </div>
	<div class="container" style = "padding: 0px">

		<!--NAV BAR-->
		<nav class="main-nav">
			<a href = "{% url 'home' %}"><img src="{% static 'home/img/title.png' %}" alt="Microsoft" class="logo"></a>
			{% if user.is_authenticated %}
			<ul class="right-menu" style="margin-top: 1rem">
				<li><a href="{% url 'announcements' %}" style = "color: #262626; text-decoration: none"><i class="fas fa-bell"></i> Announcements </a></li>
				<li><a href="{% url 'profile' %}" style = "color: #262626; text-decoration: none"><i class="fas fa-user"></i> {{user.username}} </a></li>
				<li style="cursor: pointer;">
				<form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" style="border: none; padding: 0px; background-color: white; outline: none;"><i class="fas fa-sign-out-alt"></i> Logout </button>
                </form>
            	</li>
			</ul>
			{% endif %}
			{% if messages %}
				<div role="alert" style="padding: 1rem 1rem 0; background-color: #90EE90; border-radius: 2rem;">
                <strong style="color: green; vertical-align: middle;">
				<ul class="messages">
			    {% for message in messages %}
			    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
				</ul>
					</strong>
           		 </div>
			{% endif %}
		</nav>

{% block content %} {% endblock %}

	  <br>
	  <hr>
      <!--Follow-->
      <section class="follow" style = "float: right;">
      	<p>
		  	<a href="{% url 'contact-us' %}" style='margin-left: 1rem; text-decoration: none'>
              <i class="fa fa-phone" aria-hidden="true"></i>Contact Us
            </a>
			<a href="{% url 'policy' %}" target="_blank" style='margin-left: 1rem; text-decoration: none'>
				<i class="fas fa-shield-alt"></i>Policies
			</a>
			<i class="fas fa-copyright"></i> The Code Builder
		</p>
      </section>
    </div>
   </body>
</html>

website/home/templates/home/contact-template.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Contact Frame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <style>
        body {
            margin: 0;
            padding: 0;
            min-height: 100vh;
            background: #333;
            display: flex;
            justify-content: center;
            align-items: center;   
            font-family: sans-serif;
            background-color: #f1f1f1; 
        }

        .container {
            width: 1000px;
            position: relative;
            display: flex;
            justify-content: space-between;
        }

        .container .card {
            position: relative;
            border-radius: 10px;
        }

        .container .card .icon {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #f00;
            transition: 0.7s;
            z-index: 1;
        }

        .container .card:nth-child(1) .icon {
            background: #e07768;
        }

        .container .card:nth-child(2) .icon {
            background: #6eadd4;
        }

        .container .card:nth-child(3) .icon {
            background: #4aada9;
        }


        .container .card .icon .fa {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 80px;
            transition: 0.7s;
            color: #fff;
        }

        i {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 80px;
            transition: 0.7s;
            color: #fff;
        }

        .container .card .face {
            width: 300px;
            height: 200px;
            transition: 0.5s;
        }

        .container .card .face.face1 {
            position: relative;
            background: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 1;
            transform: translateY(100px);
        }

        .container .card:hover .face.face1{
            background: #ff0057;
            transform: translateY(0px);
        }

        .container .card .face.face1 .content {
            opacity: 1;
            transition: 0.5s;
        }

        .container .card:hover .face.face1 .content {
            opacity: 1;
        }

        .container .card .face.face1 .content i{
            max-width: 100px;
        }

        .container .card .face.face2 {
            position: relative;
            background: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
            box-sizing: border-box;
            box-shadow: 0 20px 50px rgba(0,0,0,0.8);
            transform: translateY(-100px);
        }

        .container .card:hover .face.face2{
            transform: translateY(0);
        }

        .container .card .face.face2 .content p {
            margin: 0;
            padding: 0;
            text-align: center;
            color: #414141;
        }

        .container .card .face.face2 .content h3 {
            margin: 0 0 10px 0;
            padding: 0;
            color: #fff;
            font-size: 24px;
            text-align: center;
            color: #414141;
        } 

        .container a {
            text-decoration: none;
            color: #414141;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="card">
            <div class="face face1">
                <div class="content">
                    <div class="icon">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="face face2">
                <div class="content">
                    <h3>
                        <a href="https://www.instagram.com/the.code.builder/" target="_blank">@the.code.builder</a>
                    </h3>
                    <p>Connect with us on Instagram.</p>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="face face1">
                <div class="content">
                    <div class="icon">
                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="face face2">
                <div class="content">
                    <h3>
                        About Us
                    </h3>
                    <p>The Code Builder is a series of wide range of events to be held in the month of October, 2020.</p>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="face face1">
                <div class="content">
                    <div class="icon">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="face face2">
                <div class="content">
                    <h3>
                        <a href="mailto:the.code.builder0@gmail.com" target="_blank">The Code Builder</a>
                    </h3>
                    <p>Got queries? Mail us.</p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

website/home/templates/home/contact-us.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <iframe src="{% url 'contact-frame' %}" style="height:800px;width:100%" frameborder="no"></iframe>

{% endblock %}

website/home/templates/home/dashboard.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

		<br>
		<!--ShowCase-->
		<header class="showcase" style="background: url({% static 'home/img/tcb_5.png' %}) no-repeat center center/cover;">
			<img src = "{% static 'home/img/logo3.png' %}" height = "50%">
			<h2>The Code Builder</h2>
			<p>
        		The Code Builder is a series of a wide range of events to be held in the month of October 2020, completely safe and virtual.
            </p>
      		<a href="{% url 'announcements' %}" class="btn">
      			Announcements <i class="fas fa-chevron-right"></i>
      		</a>
		</header>
		<br>
		<div class = "subsec"><p>My Event Pass</p></div>
		<br>
		<hr>
		<br>
		<br>
		<section class="xbox" style="background: url({% static 'home/img/xbox.png' %}) no-repeat center center/cover;">
			<div class="content">
				<h2>Event Pass</h2>
		        <p>A single pass grants you access to everything, that will be held as a part of The Code Builder.</p>
		        <a class="btn">
		            Owned!
		        </a>
			</div>
		</section>

{% endblock %}

website/home/templates/home/home.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}
    <!--ShowCase-->
    <header class="showcase" style="background: url({% static 'home/img/tcb_5.png' %}) no-repeat center center/cover;">
        <img src="{% static 'home/img/logo3.png' %}" height="50%">
        <h2>The Code Builder</h2>
        <p>
            The Code Builder is a series of a wide range of events to be held in the month of October 2020, completely
            safe and virtual.
        </p>
        {% if not user.is_authenticated %}
            <a href="{% url 'portal' %}" class="btn">
                Sign In <i class="fas fa-chevron-right"></i>
            </a>
        {% else %}
            <a href="{% url 'dashboard' %}" class="btn">
                Dashboard <i class="fas fa-chevron-right"></i>
            </a>
        {% endif %}
    </header>
    <ul class="nav nav-tabs">
        {% for event_category in event_categories %}
            <li class="nav-item {% if forloop.first %}active{% endif %}"><a
                    class="nav-link {% if forloop.first %}active{% endif %}" data-toggle="tab"
                    href="#{{ event_category.name|slugify }}">{{ event_category.name }}</a></li>
        {% endfor %}
    </ul>

    <div class="tab-content">
        {% for event_category in event_categories %}
            {% with events=event_category.event_set.all %}
                <div id="{{ event_category.name|slugify }}"
                     class="tab-pane fade show {% if forloop.first %}active{% endif %}">
                    <div id="carouselExampleControls_{{ forloop.counter0 }}" class="carousel slide"
                         data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for event in events %}
                                <li data-target="#carouselExampleControls_{{ forloop.parentloop.counter0 }}"
                                    data-slide-to="{{ forloop.counter0 }}"
                                    class="{% if forloop.first %}active{% endif %}"></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                            {% for event in events %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <section class="carbon dark"
                                             style="background: url({% static 'home/img/comp_1.png' %}) no-repeat center center/cover;">
                                        <div class="content">
                                            <h2>{{ event.title }}</h2>
                                            <br>
                                            {% if event.image_1 %}
                                                <img src="{{ event.image_1.url }}" style="height: 7rem;">
                                            {% endif %}
                                            {% if event.image_2 %}
                                                <br><br>
                                                <img src="{{ event.image_2.url }}" style="width: 60%;">
                                            {% endif %}
                                            <br>
                                            <br>
                                            <h3> About </h3>
                                            <hr style="background-color: white;">
                                            {{ event.description }}
                                            </p>
                                            <br>
                                            {#								<h4>Companies :</h4>#}
                                            {#								<hr style="background-color: white;">#}
                                            {#								<div style="margin-left: 50%; transform: translateX(-50%)">#}
                                            {#									<figure style="display: inline-block; margin-right: 1rem">#}
                                            {#										<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Trulli" style="width:5rem; border-radius: 50%">#}
                                            {#										<figcaption style="text-align: center;">Tim</figcaption>#}
                                            {#									</figure>#}
                                            {#									<figure style="display: inline-block;">#}
                                            {#										<img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Trulli" style="width:5rem; border-radius: 50%">#}
                                            {#										<figcaption style="text-align: center;">Nancy</figcaption>#}
                                            {#									</figure>#}
                                            {#								</div>#}
                                            {#								<p>	Mentor 1 : Detail<br><br>#}
                                            {#								Mentor 2 : Detail					#}
                                            {#								<hr style="background-color: white">#}
                                            <br><br><br>
                                        </div>
                                    </section>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls_{{ forloop.counter0 }}"
                           role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls_{{ forloop.counter0 }}"
                           role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}
    </div>
    <br><br>
    {% if not user.is_authenticated %}
        <section class="xbox" style="background: url({% static 'home/img/xbox.png' %}) no-repeat center center/cover;">
            <div class="content">
                <h2>Event Pass</h2>
                <p>A single pass grants you access to everything, that will be held as a part of The Code Builder.</p>
                <a href="{% url 'portal' %}" class="btn">
                    Buy Now (₹2100) <i class="fas fa-chevron-right"></i>
                </a>
            </div>
        </section>
    {% endif %}
    <br>
    <!-- Carbon -->
    <section class="carb dark"
             style="background: url({% static 'home/img/carbon.jpg' %}) no-repeat center center/cover;">
        <div class="content">
            <h2>About Us</h2>
            <p>
                Join us for a truly enriching experience and to be a part of multiple Bootcamps, Workshops, Talks,
                Summits, Competitions and Courses, on technical as well as non technical domains, as well as
                interactions with celebrities and influencers, of the likes of Vir Das ;)
            </p>
            <p>
                The topics for these include computer science, programming, artificial intelligence, website and app
                development, game development, IoT, Cryptocurrency and Blockchain, Digital Marketing, Finance and
                Investing, Entrepreneurship, Blogging/Content writing and much much more!
                You'll be a part of something, on nearly each and everyday of the month of October 2020. </p>
            </p>
            <p>
                The amount of information will never cease existing and neither will the memory that serves the purpose.
                The more you accurately know about something, the greater will it reflect on you, be it the specialized
                skill to decode the bits or encode in bytes.
                Exploring all the encrypted data in the world is precisely what The Code Builder is all about which will
                offer an assemblage of courses for anyone to choose from to amplify their skills.
                The Code Builder aims to establish a dynamic community by catering to more than 2,500 aspiring
                Candidates.
                By providing unique insights and solutions, the Code Builder will facilitate the students to enhance
                their prospects when it comes to the programming spectrum.
            </p>
            <br><br><br>
        </div>
    </section>
    <br><br>
    <!-- Xbox -->
    {% if not user.is_authenticated %}
        <section class="xbox" style="background: url({% static 'home/img/xbox.png' %}) no-repeat center center/cover;">
            <div class="content">
                <h2>Join Our Team!</h2>
                <p>Interested? Get interned at the code builder !</p>
                <a href="http://bit.ly/thecodebuilder" class="btn">
                    Join Us <i class="fas fa-chevron-right"></i>
                </a>
            </div>
        </section>
    {% endif %}
    <br>

{% endblock %}